name: Container Image Cleaning

on:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PACKAGE_NAME: ${{ github.repository_owner }}/${{ vars.IMAGE_NAME }}
  REGISTRY_DOCKER: docker.io
  IMAGE_NAME_DOCKER: ${{ vars.DOCKERHUB_REPO }}

jobs:
  cleanup-untagged-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Delete all containers from package without tags
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          package: ${{ vars.IMAGE_NAME }}
          keep-n-untagged: 20
